version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/home/rakib/Event-Driven-e-Commerce/microservices-ecommerce-engine/app/api"  
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
